# Generated by Django 3.1.2 on 2020-11-02 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('dateconfirmed', models.DateField()),
                ('casetype', models.CharField(max_length=8)),
                ('case_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=100)),
                ('xcoord', models.FloatField()),
                ('ycoord', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('idnumber', models.CharField(max_length=12)),
                ('dateofbirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('commonname', models.CharField(max_length=20)),
                ('maxinfectiousperiod', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Viruses',
            },
        ),
        migrations.CreateModel(
            name='CaseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefrom', models.DateField()),
                ('dateto', models.DateField()),
                ('category', models.CharField(max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.case')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.location')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.patient'),
        ),
        migrations.AddField(
            model_name='case',
            name='virus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.virus'),
        ),
    ]
